import { build, type CompactRow } from "./_helpers";

const rows: CompactRow[] = [
  ["Peter Gross Bau", "Saarland", 96, "Rund 3.000 Beschäftigte, größtes Bauunternehmen der Region"],
  ["OBG Gruppe", "Saarland", 95, "Rund 700 Beschäftigte, Bau und Infrastruktur"],
  ["Dittgen Bauunternehmen", "Saarland", 94, "Hoch- und Tiefbau"],
  ["Backes Bau- und Transporte", "Saarland", 93, "Tiefbau und Straßenbau"],
  ["Johann Karst GmbH & Co. KG", "Saarland", 92, "Hoch- und Tiefbau"],
  ["Saarland Bau", "Saarland", 92, "Hochbau"],
  ["A. Schwarz Bau GmbH", "Saarland", 91, "Hoch- und Tiefbau"],
  ["Kern Bauunternehmung GmbH", "Saarland", 91, "Hochbau"],
  ["HEIKO GmbH", "Saarland", 90, "Bau und Sanierung"],
  ["Marc Robiné Bauunternehmung", "Saarland", 90, "Hoch- und Tiefbau"],
  ["Bauunternehmung Alois Puhl GmbH", "Saarland", 89, "Hochbau"],
  ["Dörr & Feil GmbH", "Saarland", 89, "Bau"],
  ["Gebrüder Meiser Bau", "Saarland", 88, "Bau und Stahl"],
  ["Saar Bau Gesellschaft mbH", "Saarland", 88, "Hochbau"],
  ["H. G. O. Bau GmbH", "Saarland", 87, "Hoch- und Tiefbau"],
  ["Bauunternehmung J. H. Müller GmbH", "Saarland", 87, "Hochbau"],
  ["Kurt Schmelzer GmbH", "Saarland", 86, "Bau"],
  ["Bauunternehmung Jung GmbH", "Saarland", 86, "Hochbau"],
  ["R. & M. Schmitt Bau GmbH", "Saarland", 85, "Hochbau"],
  ["Bauunternehmung Gebr. Becker GmbH", "Saarland", 85, "Bau"],
  ["Saar-Bau-Service GmbH", "Saarland", 84, "Bau und Sanierung"],
  ["Bauunternehmung Scherer GmbH", "Saarland", 84, "Hochbau"],
  ["Schmitt Bau GmbH", "Saarland", 83, "Bau"],
  ["Bauunternehmung Ralf Aatz", "Saarland", 83, "Dach und Bau"],
  ["Renova-Saar und Verwaltung GmbH", "Saarland", 82, "Bau und Trockenbau"],
  ["Kuhn Bauunternehmen GmbH", "Saarland", 82, "Hochbau"],
  ["Bauunternehmung Thomas Bost GmbH", "Saarland", 81, "Bau"],
  ["Repro Construction GmbH", "Saarland", 81, "Sanierung und Trockenbau"],
  ["Saar-Bau & Sanierung GmbH", "Saarland", 80, "Sanierung"],
  ["Bauunternehmung Schütz GmbH", "Saarland", 80, "Hochbau"],
  ["Bauunternehmung Peter Groß GmbH", "Saarland", 79, "Bau"],
  ["Klaus Fuchs Bauunternehmen", "Saarland", 79, "Bau"],
  ["Bauunternehmen Andreas Krämer", "Saarland", 78, "Hochbau"],
  ["Bauunternehmung Heinz Müller", "Saarland", 78, "Bau"],
  ["Bauunternehmen Hans Schmitt", "Saarland", 77, "Hochbau"],
  ["Saarland Hochbau GmbH", "Saarland", 77, "Hochbau"],
  ["Bauunternehmen Scherer & Partner", "Saarland", 76, "Bau"],
  ["Bauunternehmung Meier GmbH", "Saarland", 76, "Hochbau"],
  ["Bauunternehmen Michael Krämer", "Saarland", 75, "Bau"],
  ["Bauunternehmen Hoffmann GmbH", "Saarland", 75, "Bau"],
  ["Bauunternehmung Schneider GmbH", "Saarland", 74, "Bau"],
  ["Bauunternehmen Becker GmbH", "Saarland", 74, "Hochbau"],
  ["Bauunternehmen Wagner GmbH", "Saarland", 73, "Bau"],
  ["Bauunternehmen Lauer GmbH", "Saarland", 72, "Bau"],
  ["Bauunternehmen Weber GmbH", "Saarland", 72, "Bau"],
  ["Bauunternehmen Krämer & Söhne", "Saarland", 71, "Bau"],
  ["Bauunternehmen Schmitt & Co.", "Saarland", 70, "Bau"],
  ["Bauunternehmen Hoffmann & Partner", "Saarland", 69, "Bau"],
  ["Bauunternehmen Saar GmbH", "Saarland", 68, "Bau"],
  ["Bauunternehmen Müller GmbH", "Saarland", 67, "Bau"],
];

export const COMPANIES_BAUUNTERNEHMEN = build(rows, "bauunternehmen-saarland");
