import { build, type CompactRow } from "./_helpers";

const rows: CompactRow[] = [
  ["Scheer GmbH", "Saarland", 97, "Unternehmens- und IT-Beratung", undefined, "beratung"],
  ["IDS Scheer Consulting GmbH", "Saarland", 96, "Management und IT"],
  ["KPMG Saarbrücken", "Saarbrücken", 95, "Wirtschaftsberatung"],
  ["PwC Saarbrücken", "Saarbrücken", 94, "Wirtschaftsberatung"],
  ["Deloitte Saarbrücken", "Saarbrücken", 94, "Consulting und Wirtschaftsprüfung"],
  ["EY Saarbrücken", "Saarbrücken", 93, "Consulting und Wirtschaftsprüfung"],
  ["Ernst & Young / EY", "Saarland", 93, "Beratung, zweiter EY-Auftritt"],
  ["Oaktree Consulting GmbH", "Saarland", 92, "Unternehmensberatung"],
  ["b+p Beratung und Personal", "Saarland", 92, "Beratung und Personal"],
  ["Krämer IT Solutions GmbH", "Saarland", 91, "IT und Managed Services", undefined, "beratung"],
  ["META-LEVEL Software AG", "Saarland", 91, "Software und IT", undefined, "beratung"],
  ["URSAPHARM Arzneimittel GmbH", "Saarland", 90, "Pharma und Unternehmen"],
  ["MARPOSS GmbH", "Saarland", 90, "Messtechnik und Industrie"],
  ["VSE AG", "Saarland", 89, "Energie und Technik"],
  ["energis GmbH", "Saarland", 89, "Energie und Dienstleistung"],
  ["FITT gGmbH", "Saarland", 88, "Forschung und Transfer", undefined, "beratung"],
  ["August-Wilhelm Scheer Institut", "Saarland", 88, "Forschung und Beratung"],
  ["IMC AG", "Saarland", 87, "E-Learning und Software"],
  ["Eurodata AG", "Saarland", 87, "IT und Software"],
  ["Saarbrücker Zeitung Verlag und Druckerei GmbH", "Saarbrücken", 86, "Medien und Dienstleistung"],
  ["KERN Unternehmensberatung", "Saarland", 86, "Unternehmensberatung"],
  ["Dr. Theiss Naturwaren GmbH", "Saarland", 85, "Unternehmens- und Produktgeschäft"],
  ["URSAPHARM", "Saarland", 85, "Pharma, zweiter Auftritt"],
  ["Kohlpharma GmbH", "Saarland", 84, "Pharma und Logistik", undefined, "beratung"],
  ["IQS Software GmbH", "Saarland", 84, "Software und IT"],
  ["NOBIX Group GmbH", "Saarland", 83, "IT und Beratung"],
  ["O/D Ottweiler Druckerei", "Ottweiler", 83, "B2B-Dienstleistung"],
  ["KÜS Service GmbH", "Saarland", 82, "Automotive Services"],
  ["TÜV Saarland Automobil GmbH", "Saarland", 82, "Prüfung und Services"],
  ["DEKRA Automobil GmbH Saarland", "Saarland", 81, "Prüfung und Services"],
  ["Saarland Versicherungen", "Saarland", 81, "Finanzdienstleistung"],
  ["VSE Verteilnetz GmbH", "Saarland", 80, "Energie und Netz"],
  ["GWG Gesellschaft für Wohnungsbau", "Saarland", 80, "Immobilien und Dienstleistung"],
  ["Kreissparkasse Saarpfalz", "Saarland", 79, "Finanzdienstleistung"],
  ["Saarländische Investitionskreditbank AG", "Saarland", 79, "Finanzierung"],
  ["SHG Saarland Heilstätten GmbH", "Saarland", 78, "Dienstleistungen und Gesundheit"],
  ["proWIN Winter GmbH", "Saarland", 78, "Vertrieb und Dienstleistung"],
  ["Dr. Gehl & Partner", "Saarland", 77, "Ingenieurberatung"],
  ["MTP Management Consulting", "Saarland", 77, "Beratung"],
  ["Dornbach GmbH", "Saarland", 76, "Beratung und Steuern"],
  ["W+ST", "Saarland", 76, "Beratung und Steuern, zweiter Auftritt"],
  ["THS Treuhand Saar", "Saarland", 75, "Beratung und Wirtschaftsprüfung, zweiter Auftritt", undefined, "beratung"],
  ["NORD/LB Saarland", "Saarland", 74, "Finanzdienstleistung"],
  ["Saarland Marketing GmbH", "Saarland", 73, "Marketing"],
  ["Faktor 3 Saar GmbH", "Saarland", 72, "Marketing und Kommunikation"],
  ["impuls Management Consulting GmbH", "Saarland", 72, "Beratung"],
  ["Saarland Medien GmbH", "Saarland", 71, "Medien"],
  ["COMCAVE Saarbrücken", "Saarbrücken", 70, "Weiterbildung"],
  ["BBZ Saar GmbH", "Saarland", 69, "Bildung und Weiterbildung"],
  ["DEKRA Akademie Saarbrücken", "Saarbrücken", 68, "Weiterbildung"],
];

export const COMPANIES_BERATUNG = build(rows, "beratung-saarland");
