import { build, type CompactRow } from "./_helpers";

const rows: CompactRow[] = [
  ["proper Gebäudereinigung GmbH", "Saarbrücken", 95, "Starke Google-Bewertung 4,9/5 bei 34 Rezensionen"],
  ["Hans Bohschulte GmbH", "Saarlouis", 94, "Großer B2B-/Facility-Management-Anbieter"],
  ["STANDARD Gebäudereinigung Jacobs GmbH", "Saarbrücken", 93, "Etablierter B2B-Anbieter"],
  ["GEMIS GmbH", "Saarbrücken", 92, "Größeres B2B-Potenzial"],
  ["SIS Saar Gebäudeservice GmbH", "Völklingen", 92, "Industrie-Service-Fokus"],
  ["SIS – Saar-Industrie-Service GmbH", "Völklingen", 91, "Industrie-Service-Fokus"],
  ["OPTIMUS Gebäude-Service GmbH", "Dillingen", 91, "Wachstumsstarker B2B-Anbieter"],
  ["CELESTA Gebäudereinigung GmbH", "Homburg", 90, "B2B-Facility-Potenzial"],
  ["Express Gebäude Service GmbH", "Saarlouis", 90, "Große Reichweite"],
  ["FSG Facility-Service-Gesellschaft mbH & Co. KG", "Quierschied", 89, "Facility-Management-Potenzial"],
  ["refinas GmbH", "St. Ingbert", 89, "Größerer Anbieter"],
  ["HACO Gebäudereinigungs-GmbH", "Saarbrücken", 88, "Etablierter Anbieter"],
  ["Neue Raum- & Umweltpflege", "Saarwellingen", 88, "Regional stark"],
  ["Central GmbH Büro- und Gebäudereinigung", "Neunkirchen", 87, "Büro-Fokus"],
  ["B&L Büro- und Gebäudereinigung GmbH", "Saarbrücken", 87, "B2B-Büroreinigung"],
  ["Quick + Clean GmbH", "St. Wendel", 86, "Regional aktiv"],
  ["Arndt Gebäudereinigung", "Bexbach", 86, "Lokaler Anbieter"],
  ["Kimia GmbH", "Kleinblittersdorf", 85, "Etablierter Betrieb"],
  ["NOVUS Dienstleistungen GmbH", "Saarwellingen", 85, "Facility-Service"],
  ["NR Gebäudereinigung Dienstleistungen e.K.", "St. Wendel", 84, "Regional aktiv"],
  ["SSG Saar-Service GmbH", "Saarbrücken", 84, "Bewertung 4,4/5 bei 36 Rezensionen"],
  ["Ro.Sch-Service e.K.", "Dillingen", 83, "Lokaler Anbieter"],
  ["Gebäudereinigung Sachs GmbH", "Saarlouis", 83, "Etablierter Betrieb"],
  ["Keller Horst Gebäudereinigung GmbH", "Saarlouis", 82, "Regional aktiv"],
  ["Gebäudereinigung Neu", "Saarbrücken", 82, "Lokaler Anbieter"],
  ["B&L Gebäudereinigung", "Saarbrücken", 81, "Zweiter Auftritt der B&L Gruppe"],
  ["NL Glas- und Gebäudereinigung", "Merchweiler", 81, "Glas-Reinigung"],
  ["HCS Hölzer-Clean-Service-GmbH", "Kleinblittersdorf", 80, "Etablierter Betrieb"],
  ["SBL Dienstleistungen GmbH", "Losheim", 80, "Regional aktiv"],
  ["Oberländer Service GmbH", "Saarbrücken", 79, "Facility-Service"],
  ["3R Algenrein GmbH", "Völklingen", 79, "Spezialreinigung"],
  ["Rein Sauber Gebäudereinigung", "Saarbrücken", 78, "Lokaler Anbieter"],
  ["Gebäudereinigung Oberhofer", "Saarbrücken", 78, "Lokaler Anbieter"],
  ["Gebäudereinigung Jicha", "Wadgassen", 77, "Regional aktiv"],
  ["Xtreme Performance UG & Co. KG", "Heusweiler", 77, "Kleinerer Anbieter"],
  ["Gebäudereinigung KIWITZ", "Lebach", 76, "Lokal aktiv"],
  ["Gebäude & Reinigungsservice Saar", "Beckingen", 76, "Regional aktiv"],
  ["Ansgar Volz VGS Gebäudereinigung", "Namborn", 75, "Lokaler Anbieter"],
  ["Andreas Schmidt Gebäudereinigung", "Wadern", 75, "Lokaler Anbieter"],
  ["Gebäudereinigung Michael Netterdon", "Saarbrücken", 74, "Lokaler Anbieter"],
  ["Gebäudereinigung Günter Jost Dienstleistungen", "Saarbrücken", 74, "Lokaler Anbieter"],
  ["SEA UG", "Saarbrücken", 73, "Kleinerer Anbieter"],
  ["VGS", "Namborn", 73, "Lokal aktiv"],
  ["MK Gebäudereinigung & Dienstleistungen GmbH", "Homburg", 72, "Regional aktiv"],
  ["Gebäudereinigung Ingrid Hess", "St. Wendel", 71, "Lokaler Anbieter"],
  ["Klaus-Peter Brehmer", "Homburg", 70, "Lokaler Einzelunternehmer"],
  ["Gebäudereinigung Dieter Seibert", "Blieskastel", 69, "Lokaler Einzelunternehmer"],
  ["Norbert Staszewski", "Merchweiler", 68, "Lokaler Einzelunternehmer"],
  ["Franz-Peter Steinfeld", "Blieskastel", 67, "Lokaler Einzelunternehmer"],
  ["Müller Dirk Gebäudereinigung", "Neunkirchen", 66, "Lokaler Einzelunternehmer"],
];

export const COMPANIES_GEBAEUDEREINIGUNG = build(rows, "gebaeudereinigung-saarland");
