import { build, type CompactRow } from "./_helpers";

const rows: CompactRow[] = [
  ["GLOBAL RETOOL GROUP GmbH", "Saarland", 97, "Internationale Aktivitäten Europa/USA/China, Turn-Key-Lösungen", "https://saaris.de/kompetenzsuche/global-retool-group-gmbh/"],
  ["SEB Technology GmbH", "Saarland", 96, "Automatisierung und Technologie"],
  ["Saar Stahlbau GmbH", "Saarland", 95, "Stahl- und Anlagenbau"],
  ["Woll Maschinenbau GmbH", "Saarland", 95, "Maschinenbau"],
  ["Saar-Hartmetall und Werkzeuge GmbH", "Saarland", 94, "Werkzeuge"],
  ["Dillinger Fabrik Gelochter Bleche GmbH", "Saarland", 94, "Metalltechnik"],
  ["SGGT Hydraulik GmbH", "Saarland", 93, "Hydraulik"],
  ["Dr. Arnold Schäfer GmbH", "Saarland", 93, "Maschinen- und Anlagenbau"],
  ["Herges Stahl- und Blechbau GmbH", "Saarland", 92, "Stahlbau"],
  ["Stahl- und Apparatebau Hans Leffer GmbH", "Saarland", 92, "Apparate- und Anlagenbau"],
  ["Kunzler GmbH & Co. KG", "Saarland", 91, "Industrie und Technik"],
  ["Preinfalk GmbH", "Saarland", 91, "Getriebe und Maschinenbau"],
  ["Brabant & Lehnert Werkzeugmaschinen GmbH", "Saarland", 90, "Werkzeugmaschinen"],
  ["Dürr Assembly Products GmbH", "Saarland", 90, "Automatisierung"],
  ["Sodecia Automotive Saarlouis GmbH", "Saarlouis", 89, "Automotive"],
  ["ISL Automotive GmbH", "Saarland", 89, "Automotive Engineering"],
  ["Light Mobility Solutions GmbH", "Saarland", 89, "Automotive"],
  ["MAT Foundries Europe GmbH", "Saarland", 88, "Gießerei und Automotive"],
  ["MAT Neunkirchen GmbH", "Neunkirchen", 88, "Gießerei"],
  ["CQLT SaarGummi Deutschland GmbH", "Saarland", 88, "Gummi und Automotive"],
  ["Festo Polymer GmbH", "Saarland", 87, "Kunststofftechnik"],
  ["MELFOR GmbH", "Saarland", 87, "Automotive und Kabel"],
  ["VOIT Automotive GmbH", "Saarland", 87, "Automotive"],
  ["Adient Saarlouis Ltd. & Co. KG", "Saarlouis", 86, "Automotive"],
  ["Thyssenkrupp Automotive Body Solutions", "Saarland", 86, "Automotive"],
  ["Hörmann KG Freisen", "Freisen", 86, "Industrie und Tore"],
  ["Hörmann KG Eckelhausen", "Eckelhausen", 85, "Industrie und Tore"],
  ["KTP Kunststoff Palettentechnik GmbH", "Saarland", 85, "Kunststofftechnik"],
  ["NTC Nano Tech Coatings GmbH", "Saarland", 85, "Beschichtung und Technologie"],
  ["PM ConServ GmbH", "Saarland", 84, "Industrie-Service"],
  ["FAMIS Gesellschaft für Facility Management & Industrieservice mbH", "Saarland", 84, "Industrieservice"],
  ["Saarotec GmbH", "Saarland", 83, "Industrie- und Anlagentechnik"],
  ["Vensys Energy AG", "Saarland", 83, "Energietechnik"],
  ["MEISER Gruppe", "Saarland", 83, "Gitterroste und Stahl"],
  ["SaarGummi Neo GmbH", "Saarland", 82, "Automotive"],
  ["Bartz-Werke GmbH", "Saarland", 82, "Maschinenbau"],
  ["Scheer GmbH", "Saarland", 81, "Industrie und IT"],
  ["META-LEVEL Software AG", "Saarland", 81, "Software und IT"],
  ["A+G connect GmbH", "Saarland", 81, "IT und Netzwerk"],
  ["FITT gGmbH", "Saarland", 80, "Technologie und Transfer"],
  ["Scheid AG & Co. KG", "Saarland", 80, "Industrie und Technologie"],
  ["Kohlpharma GmbH", "Saarland", 79, "Pharma und Logistik"],
  ["Kaiser Aluminium-Umformtechnik GmbH", "Saarland", 79, "Metalltechnik"],
  ["Saarpor Klaus Eckhardt GmbH", "Saarland", 78, "Kunststoff und Industrie"],
  ["Krämer IT Solutions GmbH", "Saarland", 78, "IT und Technik"],
  ["Hager Electro GmbH & Co. KG", "Saarland", 77, "Elektrotechnik"],
  ["HYDAC International GmbH", "Saarland", 76, "Hydraulik und Industrie, ca. 1.700 Beschäftigte im Saarland"],
  ["Festo AG & Co. KG", "Saarland", 75, "Automatisierung, ca. 2.200 Beschäftigte im Saarland"],
  ["Schaeffler Technologies AG & Co. KG", "Saarland", 74, "Automotive und Maschinenbau, ca. 2.000 Beschäftigte im Saarland"],
  ["Robert Bosch GmbH – Werk Homburg", "Homburg", 73, "Automotive und Industrie, ca. 3.200 Beschäftigte im Saarland"],
];

export const COMPANIES_INDUSTRIE = build(rows, "industrie-saarland");
