import { build, type CompactRow } from "./_helpers";

const rows: CompactRow[] = [
  ["NAGEL-GROUP Saarland", "Saarland", 96, "Logistik und Lebensmittel"],
  ["Kühne + Nagel Saarland", "Saarland", 95, "Spedition und Logistik"],
  ["Robert Müller GmbH", "Saarland", 95, "Spedition und Logistik, mehrere Standorte, komplexes Portfolio"],
  ["Paul Schockemöhle Logistics", "Saarland", 94, "Logistik und Automotive"],
  ["Kohlpharma GmbH", "Saarland", 93, "Pharma und Logistik", undefined, "logistik"],
  ["Hergarten GmbH", "Saarland", 92, "Transport und Logistik"],
  ["Hoffmann Transporte GmbH", "Saarland", 92, "Spedition"],
  ["TST GmbH", "Saarland", 91, "Logistik"],
  ["FITT GmbH", "Saarland", 90, "Logistik und Dienstleistungen", undefined, "logistik"],
  ["Ludwig Zang GmbH", "Saarland", 90, "Spedition"],
  ["Saar-Moselle-Logistik GmbH", "Saarland", 89, "Logistik"],
  ["Spedition Günther + Schmitt GmbH", "Saarland", 89, "Spedition"],
  ["Kistner Spedition GmbH", "Saarland", 88, "Transport"],
  ["Saarland Spedition GmbH", "Saarland", 88, "Spedition"],
  ["Gebrüder Meiser Logistik", "Saarland", 87, "Industrie- und Transportlogistik"],
  ["Backes Bau- und Transporte GmbH", "Saarland", 87, "Transport und Bau", undefined, "logistik"],
  ["Klein Transport GmbH", "Saarland", 86, "Transport"],
  ["Müller Transporte GmbH", "Saarland", 86, "Transport"],
  ["Saar Express GmbH", "Saarland", 85, "Logistik"],
  ["Transports Mertes", "Saarland", 85, "Transport"],
  ["H. P. Schmitz GmbH", "Saarland", 84, "Spedition"],
  ["Göttel Transporte GmbH", "Saarland", 84, "Transport"],
  ["Schneider Logistik GmbH", "Saarland", 83, "Logistik"],
  ["Saarlog GmbH", "Saarland", 83, "Logistik"],
  ["HLS Logistik GmbH", "Saarland", 82, "Logistik"],
  ["Meyer Logistik GmbH", "Saarland", 82, "Transport und Logistik"],
  ["Bauer Transporte GmbH", "Saarland", 81, "Transport"],
  ["Klein & Sohn Transporte", "Saarland", 81, "Transport"],
  ["Schmitt Transporte GmbH", "Saarland", 80, "Transport"],
  ["Saar Transporte GmbH", "Saarland", 80, "Transport"],
  ["Hoffmann Logistik GmbH", "Saarland", 79, "Logistik"],
  ["Wagner Spedition GmbH", "Saarland", 79, "Spedition"],
  ["Koch Transporte GmbH", "Saarland", 78, "Transport"],
  ["Becker Logistik GmbH", "Saarland", 78, "Logistik"],
  ["Huber Transporte GmbH", "Saarland", 77, "Transport"],
  ["Saar-Pfalz Logistik GmbH", "Saarland", 77, "Logistik"],
  ["Roth Transporte GmbH", "Saarland", 76, "Transport"],
  ["Schäfer Transporte GmbH", "Saarland", 76, "Transport"],
  ["Kessler Logistik GmbH", "Saarland", 75, "Logistik"],
  ["Maurer Transporte GmbH", "Saarland", 75, "Transport"],
  ["Lauer Spedition GmbH", "Saarland", 74, "Spedition"],
  ["Schneider Transporte GmbH", "Saarland", 74, "Transport"],
  ["Weber Logistik GmbH", "Saarland", 73, "Logistik"],
  ["Saarland Transport & Logistik GmbH", "Saarland", 73, "Logistik"],
  ["Neunkircher Spedition GmbH", "Neunkirchen", 72, "Spedition"],
  ["Saarbrücker Transport GmbH", "Saarbrücken", 71, "Transport"],
  ["Homburger Logistik GmbH", "Homburg", 71, "Logistik"],
  ["Saarlouis Transport GmbH", "Saarlouis", 70, "Transport"],
  ["Völklingen Logistik GmbH", "Völklingen", 69, "Logistik"],
  ["St. Wendel Transporte GmbH", "St. Wendel", 68, "Transport"],
];

export const COMPANIES_LOGISTIK = build(rows, "logistik-saarland");
