import { build, type CompactRow } from "./_helpers";

const rows: CompactRow[] = [
  ["DORNBACH Saarbrücken", "Saarbrücken", 95, "Rund 80 Mitarbeiter, ca. 30 Berufsträger", "https://www.dornbach.de/de/saarbruecken.html"],
  ["THS Treuhand Saar", "Saarland", 94, "Über 190 Mitarbeiter an 5 Standorten", "https://www.treuhand-saar.de"],
  ["Gottschalk & Partner", "Saarland", 94, "Wirtschaftsprüfung und Recht"],
  ["W+ST Saarbrücken", "Saarbrücken", 93, "Über 30 Mitarbeiter am Standort, Gruppe mit 100+ Berufsträgern", "https://www.wst.de/standorte/saarbruecken/w-st-wub-steuerberatungsgesellschaft-mbh/"],
  ["Stahl & Hoffmann", "Saarland", 89, "Steuer, Wirtschaftsprüfung, Wirtschaft"],
  ["Schaller & Scherer", "Saarland", 89, "Steuer- und Gesellschaftsrecht"],
  ["Peehs & Kollegen", "Saarland", 88, "Steuer und Recht"],
  ["HSP STEUER Saarbrücken", "Saarbrücken", 87, "Steuerberatung"],
  ["Kanzlei Klein Steuerberater PartGmbB", "Saarland", 87, "Steuerberatung"],
  ["Peehs und Kollegen", "Saarland", 86, "Zweiter Auftritt Peehs, Steuerberatung und Recht"],
  ["W+ST WUB Steuerberatungsgesellschaft", "Saarland", 86, "Steuerberatung im W+ST Verbund"],
  ["Kanzlei Hoffmann Steuerberatung", "Saarland", 84, "Steuerberatung"],
  ["Zimmer & Zimmer GbR", "Saarland", 84, "Steuern und Recht"],
  ["Kanzlei Sändig", "Saarland", 82, "Steuerrecht"],
  ["Dorothee Schirra Steuerberaterkanzlei", "Saarland", 82, "Steuerberatung"],
  ["Steuerkanzlei Hirt", "Saarland", 81, "Steuerberatung"],
  ["Steuerkanzlei Dr. Jürgen Müller", "Saarland", 81, "Steuerberatung"],
  ["Kanzlei Ralf Müller", "Saarland", 80, "Steuerberatung"],
  ["Steuerberater Thomas Schmitt", "Saarland", 80, "Steuerberatung"],
  ["Kanzlei Schmitt & Partner", "Saarland", 79, "Steuerberatung"],
  ["Steuerkanzlei Becker", "Saarland", 79, "Steuerberatung"],
  ["Kanzlei Scherer", "Saarland", 78, "Steuerberatung"],
  ["Steuerberatungsgesellschaft Saarland mbH", "Saarland", 78, "Steuerberatung"],
  ["Kanzlei Weber & Partner", "Saarland", 77, "Steuerberatung"],
  ["Steuerkanzlei Hoffmann & Kollegen", "Saarland", 77, "Steuerberatung"],
  ["Kanzlei Wagner", "Saarland", 76, "Steuerberatung"],
  ["Steuerberatung Saar GmbH", "Saarland", 76, "Steuerberatung"],
  ["Kanzlei Schneider", "Saarland", 75, "Steuerberatung"],
  ["Steuerkanzlei Klein & Partner", "Saarland", 75, "Steuerberatung"],
  ["Steuerberater Müller & Partner", "Saarland", 74, "Steuerberatung"],
  ["Steuerkanzlei Saarlouis", "Saarlouis", 73, "Steuerberatung"],
  ["Steuerkanzlei Neunkirchen", "Neunkirchen", 71, "Steuerberatung"],
  ["Steuerkanzlei St. Wendel", "St. Wendel", 69, "Steuerberatung"],
];

export const COMPANIES_STEUERBERATER = build(rows, "steuerberater-saarland");
